/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.cadastro_questaoDao;
import dao.cadastro_recomendacaoDao;
import java.util.List;
import javax.swing.JOptionPane;
import model.questao;
import model.recomendacao;

/**
 *
 * @author Cliente
 */
public class resposta_da_questão extends javax.swing.JFrame {
     private int num;

    /**
     * Creates new form resposta_da_questão
     */
    public resposta_da_questão() {
        initComponents();
    }

    public resposta_da_questão(int nu, boolean resp) {
        initComponents();
        mostranome(nu);
        mostraResposta(nu);
        mostraR(resp);
        num=nu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ano_nome = new javax.swing.JTextField();
        resposta_correta = new javax.swing.JTextField();
        comentario = new javax.swing.JTextField();
        link = new javax.swing.JTextField();
        proxima = new javax.swing.JButton();
        resposta_clara = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ano_nome.setText("nome/ano da prova ");
        ano_nome.setEnabled(false);

        resposta_correta.setText("resposta correta ");
        resposta_correta.setEnabled(false);

        comentario.setText("comentario");
        comentario.setEnabled(false);
        comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentarioActionPerformed(evt);
            }
        });

        link.setText("link de video");
        link.setEnabled(false);

        proxima.setText("proxima questao");
        proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximaActionPerformed(evt);
            }
        });

        resposta_clara.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ano_nome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comentario)
                            .addComponent(resposta_clara)
                            .addComponent(resposta_correta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(link))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(proxima, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ano_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta_clara, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta_correta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(proxima)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comentarioActionPerformed

    private void proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximaActionPerformed
        // TODO add your handling code here:
            num++;
            cadastro_questaoDao pegaList = new cadastro_questaoDao();
            List<questao>consulta = pegaList.listaDeQuestoes();
            if(num>=consulta.size()){
                JOptionPane.showMessageDialog(null,"fim das questoes");
                 entrada entra=new entrada();
                 entra.setLocationRelativeTo(null);
                 entra.setVisible(true); 
                 dispose();
            }else{
            tela_de_exibição_de_questão respo = new tela_de_exibição_de_questão(num);
            respo.setLocationRelativeTo(null);
            respo.setVisible(true); 
            dispose();
            }
    }//GEN-LAST:event_proximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resposta_da_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resposta_da_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resposta_da_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resposta_da_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resposta_da_questão().setVisible(true);
            }
        });
    }
    public void mostranome(int nu){
        cadastro_questaoDao pegaList = new cadastro_questaoDao(); 
        List<questao>consulta = pegaList.listaDeQuestoes();
        ano_nome.setText((String) consulta.get(nu).getNome()+ "/" +consulta.get(nu).getAno());
        resposta_correta.setText((String)consulta.get(nu).getResposta_1());
    }
    public void mostraResposta(int num){
        cadastro_recomendacaoDao pegaLista =new cadastro_recomendacaoDao();
        List<recomendacao>consultaReco=pegaLista.listaDeRecomendacao();
        comentario.setText((String)consultaReco.get(num).getComentario());
        link.setText((String)consultaReco.get(num).getLink());
    }
    public void mostraR(boolean re){
        if(re==true){
            resposta_clara.setText("você acerto a questão");
        }
        else{
            resposta_clara.setText("você errou a questão");;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano_nome;
    private javax.swing.JTextField comentario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField link;
    private javax.swing.JButton proxima;
    private javax.swing.JTextField resposta_clara;
    private javax.swing.JTextField resposta_correta;
    // End of variables declaration//GEN-END:variables
}
