/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.cadastro_questaoDao;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import model.questao;

/**
 *
 * @author Cliente
 */
public class tela_de_exibição_de_questão extends javax.swing.JFrame {
    private int nume;
    private boolean resp = false;
    private int numero;
    private List<Integer> ll = new ArrayList<Integer>();
    /**
     * Creates new form tela_de_exibição_de_questão
     */
    public tela_de_exibição_de_questão() {
        initComponents();
        mostaper(nume);
    }
    public tela_de_exibição_de_questão(int nu) {
        initComponents();
        nume=nu;
        mostaper(nume);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_ano = new javax.swing.JTextField();
        enunciado = new javax.swing.JTextField();
        verificar = new javax.swing.JButton();
        CB1 = new javax.swing.JCheckBox();
        CB2 = new javax.swing.JCheckBox();
        CB3 = new javax.swing.JCheckBox();
        CB4 = new javax.swing.JCheckBox();
        CB5 = new javax.swing.JCheckBox();
        resposta1 = new javax.swing.JTextField();
        resposta2 = new javax.swing.JTextField();
        resposta3 = new javax.swing.JTextField();
        resposta4 = new javax.swing.JTextField();
        resposta5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("tela de exibição de questão"));

        nome_ano.setText("nome/ano da prova ");
        nome_ano.setEnabled(false);

        enunciado.setText("enunciado ");
        enunciado.setEnabled(false);
        enunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciadoActionPerformed(evt);
            }
        });

        verificar.setText("verificar");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });

        CB1.setText("jCheckBox1");
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });

        CB2.setText("jCheckBox2");
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });

        CB3.setText("jCheckBox3");
        CB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB3ActionPerformed(evt);
            }
        });

        CB4.setText("jCheckBox4");
        CB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB4ActionPerformed(evt);
            }
        });

        CB5.setText("jCheckBox5");
        CB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB5ActionPerformed(evt);
            }
        });

        resposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(verificar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enunciado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nome_ano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CB3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CB4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resposta3)
                                    .addComponent(resposta4)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resposta1)
                            .addComponent(resposta2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CB5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resposta5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB1)
                    .addComponent(resposta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB2)
                    .addComponent(resposta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB3)
                    .addComponent(resposta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB4)
                    .addComponent(resposta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB5)
                    .addComponent(resposta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(verificar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enunciadoActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
        //responsavel por permitir marcar apenas uma opçao
        CB2.setSelected(false);
        CB3.setSelected(false);
        CB4.setSelected(false);
        CB5.setSelected(false);
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
        // TODO add your handling code here:
        //responsavel por permitir marcar apenas uma opçao
        CB1.setSelected(false);
        CB3.setSelected(false);
        CB4.setSelected(false);
        CB5.setSelected(false);
    }//GEN-LAST:event_CB2ActionPerformed

    private void CB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB3ActionPerformed
        // TODO add your handling code here:
        //responsavel por permitir marcar apenas uma opçao
        CB1.setSelected(false);
        CB2.setSelected(false);
        CB4.setSelected(false);
        CB5.setSelected(false);
    }//GEN-LAST:event_CB3ActionPerformed

    private void CB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB4ActionPerformed
        // TODO add your handling code here:
        //responsavel por permitir marcar apenas uma opçao
        CB1.setSelected(false);
        CB2.setSelected(false);
        CB3.setSelected(false);
        CB5.setSelected(false);
    }//GEN-LAST:event_CB4ActionPerformed

    private void CB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB5ActionPerformed
        // TODO add your handling code here:
        //responsavel por permitir marcar apenas uma opçao
        CB1.setSelected(false);
        CB2.setSelected(false);
        CB3.setSelected(false);
        CB4.setSelected(false);
    }//GEN-LAST:event_CB5ActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        // TODO add your handling code here:
        if(CB1.isSelected()==true||CB2.isSelected()==true||CB3.isSelected()==true||CB4.isSelected()==true||CB5.isSelected()==true){
           int uu=0;
           if(CB1.isSelected()==true){
               uu=1;
           }
           if(CB2.isSelected()==true){
               uu=2;
           }
           if(CB3.isSelected()==true){
               uu=3;
           }
           if(CB4.isSelected()==true){
               uu=4;
           }
           if(CB5.isSelected()==true){
               uu=5;
           }
           if(uu==numero){
               resp=true;
           }if(uu!=numero){
               resp=false;
           }
            resposta_da_questão respo = new resposta_da_questão(nume,resp);
            respo.setLocationRelativeTo(null);
            respo.setVisible(true); 
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"marque uma resposta");
        }
        
    }//GEN-LAST:event_verificarActionPerformed

    private void resposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resposta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_de_exibição_de_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_de_exibição_de_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_de_exibição_de_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_de_exibição_de_questão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_de_exibição_de_questão().setVisible(true);
            }
        });
    }
    public void mostaper(int nu){ 
        List<Integer> lis = new ArrayList<Integer>();
        String rep1,rep2,rep3,rep4,rep5;
        int a,b,c,d,e;
        cadastro_questaoDao pegaList = new cadastro_questaoDao();
        List<questao>consulta = pegaList.listaDeQuestoes();
            nome_ano.setText((String) consulta.get(nu).getNome()+ "/" +consulta.get(nu).getAno());
            enunciado.setText((String)consulta.get(nu).getEnunciado());
            rep1=consulta.get(nu).getResposta_1();
            rep2=consulta.get(nu).getResposta_2();
            rep3=consulta.get(nu).getResposta_3();
            rep4=consulta.get(nu).getResposta_4();
            rep5=consulta.get(nu).getResposta_5();
            lis=sorteio();
            a=lis.get(0);
            b=lis.get(1);
            c=lis.get(2);
            d=lis.get(3);
            e=lis.get(4);
            switch(a){
                case 1:
                    resposta1.setText(rep1);
                    numero=1;
                break;
                case 2:
                    resposta2.setText(rep1);
                    numero=2;
                break;
                case 3:
                    resposta3.setText(rep1);
                    numero=3;
                break;
                case 4:
                    resposta4.setText(rep1);
                    numero=4;
                break;
                case 5:
                    resposta5.setText(rep1);
                    numero=5;
                break;  
            }
            
            switch(b){
                case 1:
                    resposta1.setText(rep2);
                break;
                case 2:
                    resposta2.setText(rep2);
                break;
                case 3:
                    resposta3.setText(rep2);
                break;
                case 4:
                    resposta4.setText(rep2);
                break;
                case 5:
                    resposta5.setText(rep2);
                break;
                
            }
            switch(c){
                case 1:
                    resposta1.setText(rep3);
                break;
                case 2:
                    resposta2.setText(rep3);
                break;
                case 3:
                    resposta3.setText(rep3);
                break;
                case 4:
                    resposta4.setText(rep3);
                break;
                case 5:
                    resposta5.setText(rep3);
                break;
            }
            switch(d){
                case 1:
                    resposta1.setText(rep4);
                break;
                case 2:
                    resposta2.setText(rep4);
                break;
                case 3:
                    resposta3.setText(rep4);
                break;
                case 4:
                    resposta4.setText(rep4);
                break;
                case 5:
                    resposta5.setText(rep4);
                break;
            }
            switch(e){
                case 1:
                    resposta1.setText(rep5);
                break;
                case 2:
                    resposta2.setText(rep5);
                break;
                case 3:
                    resposta3.setText(rep5);
                break;
                case 4:
                    resposta4.setText(rep5);
                break;
                case 5:
                    resposta5.setText(rep5);
                break;
                
            }
    }
    public List<Integer> sorteio(){
        List<Integer> lista = new ArrayList<Integer>();
        Integer valor;
        while(lista.size() < 5) {
            valor = 1 + (int) (Math.random() * 5);
            // se o número for distinto
            if(!lista.contains(valor)) {
                    lista.add(valor);
            }
        }
      return lista;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB1;
    private javax.swing.JCheckBox CB2;
    private javax.swing.JCheckBox CB3;
    private javax.swing.JCheckBox CB4;
    private javax.swing.JCheckBox CB5;
    private javax.swing.JTextField enunciado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_ano;
    private javax.swing.JTextField resposta1;
    private javax.swing.JTextField resposta2;
    private javax.swing.JTextField resposta3;
    private javax.swing.JTextField resposta4;
    private javax.swing.JTextField resposta5;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables

    public int getNume() {
        return nume;
    }

    public void setNume(int nu) {
        this.nume = nume;
    }

    public boolean isResp() {
        return resp;
    }

    public void setResp(boolean resp) {
        this.resp = resp;
    }

}
